### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by drelbert** [drelbert/ai-roast#3]
console message = 

/api/roast/d7430c0f-997d-4df9-9b09-ea72445eb47f:1     Failed to load resource: the server responded with a status of 500 ()

488-ba1058e4106ae61e.js:1 TypeError: Cannot destructure property 'roast' of 'u' as it is undefined.
    at i (https://roastlab.vercel.app/_next/static/chunks/app/(dashboard)/roast/%5Bid%5D/page-c8b280f20a5b264f.js:1:511)
    at rs (bce60fc1-afa5e7572dbd343d.js:9:38881)
    at lg (bce60fc1-afa5e7572dbd343d.js:9:54281)
    at iv (bce60fc1-afa5e7572dbd343d.js:9:112693)
    at oR (bce60fc1-afa5e7572dbd343d.js:9:90085)
    at bce60fc1-afa5e7572dbd343d.js:9:89934
    at oD (bce60fc1-afa5e7572dbd343d.js:9:89941)
    at ow (bce60fc1-afa5e7572dbd343d.js:9:87643)
    at ok (bce60fc1-afa5e7572dbd343d.js:9:86505)
    at E (488-ba1058e4106ae61e.js:25:1398)

**Comment by drelbert** [comment]
Occurs when entering text in the  roast/id <RoastEditor> page/component. 

possibly related: 
in dev when editing get this error = 

components/RoastEditor.tsx (18:10) @ roast

Unhandled Runtime Error
TypeError: Cannot destructure property 'roast' of 'analysis' as it is undefined.
